
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: esh_test_app_development
  pool: 5

test:
  host: 
  adapter: postgresql
  encoding: unicode
  database: esh_test_app_test
  pool: 5
  

production:
  host: 
  adapter: postgresql
  encoding: unicode
  database: esh_test_app_production
  pool: 5
  

